CREATE TABLE BATCH_LIST (
    BATCH varchar2(10) NOT NULL PRIMARY KEY
    );

CREATE TABLE LAB_GROUPS (
    BATCH varchar2(10),
    LAB_GROUP varchar2(10) NOT NULL PRIMARY KEY,
    CONSTRAINT LG_FK  FOREIGN KEY (BATCH) REFERENCES BATCH_LIST(BATCH)
    );

CREATE TABLE FACULTY_LIST (
    TEACHER_NAME varchar2(50) NOT NULL,
    TEACHER_CODE varchar2(5) NOT NULL PRIMARY KEY
    );
    
CREATE TABLE DAY_LIST (
    DAY varchar2(10) NOT NULL PRIMARY KEY
    );

CREATE TABLE ROOM_LIST (
    ROOM_NO varchar2(10) NOT NULL PRIMARY KEY
    );

CREATE TABLE CLASS_TIME_SLOTS (
    CLASS_TIME_SLOT varchar2(20) NOT NULL PRIMARY KEY
    );

CREATE TABLE LAB_TIME_SLOTS (
    LAB_TIME_SLOT varchar2(20) NOT NULL PRIMARY KEY
    );

CREATE TABLE COURSE_LIST (
    COURSE_TITLE varchar2(50) NOT NULL,
    COURSE_SHORT varchar2(25) NOT NULL,
    COURSE_CODE varchar2(10) NOT NULL PRIMARY KEY
    );

CREATE TABLE CLASS_ROUTINE (
    DAY varchar2(10),
    COURSE_SHORT varchar2(25),
    COURSE_CODE varchar2(10),
    ROOM_NO varchar2(10),
    TEACHER_CODE varchar2(5),
    BATCH varchar2(10),
    LAB_TIME_SLOT varchar2(20),
    
    CONSTRAINT CL_FK1 FOREIGN KEY (DAY) REFERENCES DAY_LIST(DAY),
    CONSTRAINT CL_FK2 FOREIGN KEY (COURSE_CODE) REFERENCES COURSE_LIST(COURSE_CODE),
    CONSTRAINT CL_FK3 FOREIGN KEY (ROOM_NO) REFERENCES ROOM_LIST(ROOM_NO),
    CONSTRAINT CL_FK4 FOREIGN KEY (TEACHER_CODE) REFERENCES FACULTY_LIST(TEACHER_CODE),
    CONSTRAINT CL_FK5 FOREIGN KEY (BATCH) REFERENCES BATCH_LIST(BATCH),
    CONSTRAINT CL_FK6 FOREIGN KEY (CLASS_TIME_SLOT) REFERENCES CLASS_TIME_SLOTS(CLASS_TIME_SLOT),
    CONSTRAINT CL_PK PRIMARY KEY (
        DAY,
        COURSE_SHORT,
        COURSE_CODE,
        ROOM_NO,
        TEACHER_CODE,
        BATCH,
        CLASS_TIME_SLOT)
    );

CREATE TABLE LAB_ROUTINE (
    DAY varchar2(10),
    COURSE_SHORT varchar2(25),
    COURSE_CODE varchar2(10),
    ROOM_NO varchar2(10),
    TEACHER_CODE varchar2(5),
    LAB_GROUP varchar2(10),
    LAB_TIME_SLOT varchar2(20),
    
    CONSTRAINT LB_FK1 FOREIGN KEY (DAY) REFERENCES DAY_LIST(DAY),
    CONSTRAINT LB_FK3 FOREIGN KEY (COURSE_CODE) REFERENCES COURSE_LIST(COURSE_CODE),
    CONSTRAINT LB_FK4 FOREIGN KEY (ROOM_NO) REFERENCES ROOM_LIST(ROOM_NO),
    CONSTRAINT LB_FK5 FOREIGN KEY (TEACHER_CODE) REFERENCES FACULTY_LIST(TEACHER_CODE),
    CONSTRAINT LB_FK6 FOREIGN KEY (BATCH) REFERENCES BATCH_LIST(BATCH),
    CONSTRAINT LB_FK7 FOREIGN KEY (LAB_TIME_SLOT) REFERENCES LAB_TIME_SLOTS(LAB_TIME_SLOT),
    CONSTRAINT LB_PK PRIMARY KEY (
        DAY,
        COURSE_SHORT,
        COURSE_CODE,
        ROOM_NO,
        TEACHER_CODE,
        BATCH,
        LAB_TIME_SLOT)
    );

DROP TABLE LAB_GROUPS;
DROP TABLE CLASS_LIST;
DROP TABLE TEACHER_LIST;
DROP TABLE DAY_LIST;
DROP TABLE ROOM_LIST;
DROP TABLE CLASS_TIME_SLOTS;
DROP TABLE LAB_TIME_SLOTS;
DROP TABLE COURSE_LIST;
DROP TABLE BATCH_LIST;
