package ShortR;


import InterfaceOne.*;
import static InterfaceOne.Base_1.ACON_2;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A.R. Nobel
 */
public class Access_2_Backup extends javax.swing.JFrame {

    /**
     * Creates new form AC_2
     * @param Database
     */
    public Access_2_Backup() {
        initComponents();
        Initialize();
    }
    
    private void Initialize(){

        setSize(800,500);
        setResizable(false);
        setDefaultCloseOperation(Base_1.DISPOSE_ON_CLOSE);
        
        //Faculty List +
        try{
        Statement ST = ACON_2.createStatement();
        ResultSet RS = ST.executeQuery("SELECT MEMBER_NAME FROM FACULTY_LIST");
            while(RS.next())
            {
                FacultyList.addItem(RS.getString("MEMBER_NAME"));
            }
        RS = ST.executeQuery("SELECT BATCH FROM BATCH_LIST");
            while(RS.next())
            {
                BatchList.addItem(RS.getString("BATCH"));
            }
        RS = ST.executeQuery("SELECT DAY FROM DAY_LIST");
            while(RS.next())
            {
                DayList.addItem(RS.getString("DAY"));
            } 
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    private void tabInit(String TableName,String Caller)
    {
        try{
        Statement ST = ACON_2.createStatement();
        ResultSet RS = null;
        
        if(Caller.equals("Faculty"))
            RS = ST.executeQuery("SELECT * FROM CLASS_ROUTINE NATURAL JOIN FACULTY_LIST NATURAL JOIN ROOM_LIST WHERE MEMBER_NAME ='"+TableName+"'");;
        if(Caller.equals("Batch"))
            RS = ST.executeQuery("SELECT * FROM CLASS_ROUTINE NATURAL JOIN FACULTY_LIST NATURAL JOIN ROOM_LIST WHERE BATCH ='"+TableName+"'");;
        if(Caller.equals("Day"))
            RS = ST.executeQuery("SELECT * FROM CLASS_ROUTINE NATURAL JOIN FACULTY_LIST NATURAL JOIN ROOM_LIST WHERE DAY ='"+TableName+"'");
        
        ResultSetMetaData RSMD = RS.getMetaData();
        int COL = RSMD.getColumnCount();
        DefaultTableModel TM = new DefaultTableModel();
        
        for(int i = 1; i <= COL; i++)
        {
            TM.addColumn(RSMD.getColumnName(i));
        }
        
        if(Caller.equals("Faculty"))
            FacultyRoutine.setModel(TM);
        if(Caller.equals("Batch"))
            BatchRoutine.setModel(TM);
        if(Caller.equals("Day"))
            DayRoutine.setModel(TM);
        
        FacultyRoutine.setRowHeight(50);
        BatchRoutine.setRowHeight(50);
        DayRoutine.setRowHeight(50);
        
        while(RS.next()) {
        TM.addRow(new Object[] {   "<html>"+RS.getString(1)+"<br>"+RS.getString(2) 
                        , RS.getString(2)
                        , RS.getString(3)
                        , RS.getString(4)
                        , RS.getString(5)
                        , RS.getString(6)
                        , RS.getString(7)
                        , RS.getString(8)
                        , RS.getString(9)
                        , RS.getString(10) });
 }
        
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AccessPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BatchRoutine = new javax.swing.JTable();
        Text_1 = new javax.swing.JLabel();
        BatchList = new javax.swing.JComboBox<>();
        ExportBatch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Text_2 = new javax.swing.JLabel();
        FacultyList = new javax.swing.JComboBox<>();
        ExportFaculty = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        FacultyRoutine = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Text_4 = new javax.swing.JLabel();
        DayList = new javax.swing.JComboBox<>();
        ExportBatch1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        DayRoutine = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setText("Test");

        BatchRoutine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(BatchRoutine);

        Text_1.setText("Select Batch :");
        Text_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BatchList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatchListActionPerformed(evt);
            }
        });

        ExportBatch.setText("Export");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text_1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BatchList, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addComponent(ExportBatch))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_1)
                    .addComponent(BatchList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportBatch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Batch", jPanel2);

        Text_2.setText("Select Faculty Member :");
        Text_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        FacultyList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacultyListActionPerformed(evt);
            }
        });

        ExportFaculty.setText("Export");

        FacultyRoutine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(FacultyRoutine);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text_2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FacultyList, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExportFaculty))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_2)
                    .addComponent(FacultyList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportFaculty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Faculty", jPanel3);

        Text_4.setText("Select Day :");
        Text_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayListActionPerformed(evt);
            }
        });

        ExportBatch1.setText("Export");

        DayRoutine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(DayRoutine);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Text_4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DayList, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addComponent(ExportBatch1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_4)
                    .addComponent(DayList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportBatch1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Day Summary", jPanel4);

        javax.swing.GroupLayout AccessPanelLayout = new javax.swing.GroupLayout(AccessPanel);
        AccessPanel.setLayout(AccessPanelLayout);
        AccessPanelLayout.setHorizontalGroup(
            AccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        AccessPanelLayout.setVerticalGroup(
            AccessPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccessPanelLayout.createSequentialGroup()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AccessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BatchListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatchListActionPerformed
        // TODO add your handling code here:
        tabInit(BatchList.getSelectedItem().toString(),"Batch");
    }//GEN-LAST:event_BatchListActionPerformed

    private void DayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayListActionPerformed
        // TODO add your handling code here:
        tabInit(DayList.getSelectedItem().toString(),"Day");
    }//GEN-LAST:event_DayListActionPerformed

    private void FacultyListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacultyListActionPerformed
        // TODO add your handling code here:
       tabInit(FacultyList.getSelectedItem().toString(),"Faculty");
    }//GEN-LAST:event_FacultyListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Access_2_Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Access_2_Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Access_2_Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Access_2_Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Access_2_Backup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccessPanel;
    private javax.swing.JComboBox<String> BatchList;
    private javax.swing.JTable BatchRoutine;
    private javax.swing.JComboBox<String> DayList;
    private javax.swing.JTable DayRoutine;
    private javax.swing.JButton ExportBatch;
    private javax.swing.JButton ExportBatch1;
    private javax.swing.JButton ExportFaculty;
    private javax.swing.JComboBox<String> FacultyList;
    private javax.swing.JTable FacultyRoutine;
    private javax.swing.JLabel Text_1;
    private javax.swing.JLabel Text_2;
    private javax.swing.JLabel Text_4;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
